site_name: My Simple Notes

nav:
  - Home: index.md
  - Current Problem: Memory/current_problem.md

theme:
  name: mkdocs

markdown_extensions:
  - fenced_code 
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
